echo "Starting STAR";
projet=..;
ref_fasta=$projet/ref_genome/*.fasta;
HNCWU=$projet/rnaseq_reads/Qm6a_Glucose_HNCWU_R1.fastq;
HNCWW=$projet/rnaseq_reads/Qm6a_Glucose_HNCWW_R1.fastq;
HNCWZ=$projet/rnaseq_reads/Qm6a_Lactose_HNCWZ_R1.fastq;
HNCXA=$projet/rnaseq_reads/Qm6a_Glucose_HNCXA_R1.fastq;
genomeDir=$projet/genomeDir;
annot=$projet/ref_genome/*.gff;
echo "Generating Genome Indexes";
#STAR --runThreadN 1 --sjdbGTFfile $annot --sjdbGTFfeatureExon CDS  --sjdbGTFtagExonParentTranscript Parent --runMode genomeGenerate --genomeDir $genomeDir  --genomeFastaFiles $ref_fasta;
echo "Mapping RNASeq reads to genome";
STAR --runThreadN 1 --genomeDir $genomeDir --readFilesIn $HNCWU;